version: '3.2'
volumes:
  db:
  influxdb:
services:
  influxdb:
    image: influxdb:1.8.3-alpine
    volumes:
      - type: volume
        source: influxdb
        target: /var/lib/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=killbill
      - INFLUXDB_ADMIN_PASSWORD=killbill
      - INFLUXDB_USER=killbill
      - INFLUXDB_USER_PASSWORD=killbill
      - INFLUXDB_DB=killbill
    networks:
      - elk
  grafana:
    image: grafana/grafana:7.2.0
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks:
      - elk
  killbill:
    image: killbill/killbill:0.24.3
    ports:
      - "8080:8080"
    environment:
      - KILLBILL_DAO_URL=jdbc:mysql://db:3306/killbill
      - KILLBILL_DAO_USER=root
      - KILLBILL_DAO_PASSWORD=killbill
      - KILLBILL_METRICS_INFLUXDB=true
      - KILLBILL_METRICS_INFLUXDB_HOST=influxdb
      - KILLBILL_METRICS_INFLUXDB_PORT=8086
  kaui:
    image: killbill/kaui:2.0.11
    ports:
      - "9090:8080"
    environment:
      - KAUI_CONFIG_DAO_URL=jdbc:mysql://db:3306/kaui
      - KAUI_CONFIG_DAO_USER=root
      - KAUI_CONFIG_DAO_PASSWORD=killbill
      - KAUI_KILLBILL_URL=http://killbill:8080
      - KAUI_KILLBILL_API_KEY=bob
      - KAUI_KILLBILL_API_SECRET=lazar
  db:
    image: killbill/mariadb:0.24
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=killbill
networks:
  elk:
    driver: bridge